Final Project Submission

Student name: Michelle Wangui Maina

Student pace: Part-time

Scheduled project review date/time: 28th July 2025

Instructor name: Fidelis Wanalwenge

1. **Import the Relevant Library**

In [11]:
import pandas as pd

**2. Load the Data into a DataFrame**

In [19]:
aviation_data = pd.read_csv(r'\Users\mmaina\Documents\Flatiron\Project\Aviation_Data.csv')
aviation_data.head()

C:\Users\mmaina\AppData\Local\Temp\ipykernel_13840\283294529.py:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  aviation_data = pd.read_csv(r'\Users\mmaina\Documents\Flatiron\Project\Aviation_Data.csv')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

**3. Get the information on the file**

In [6]:
aviation_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        73659 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.4+ MB

**4. Data Cleaning**

In [20]:
#Dropping columns with many missing values

aviation_data.drop(columns=['Latitude','Longitude', 'Schedule', 'Air.carrier', 'Airport.Code','Airport.Name' ], inplace=True)

In [21]:
aviation_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Injury.Severity         87889 non-null  object
 7   Aircraft.damage         85695 non-null  object
 8   Aircraft.Category       32287 non-null  object
 9   Registration.Number     87507 non-null  object
 10  Make                    88826 non-null  object
 11  Model                   88797 non-null  object
 12  Amateur.Built           88787 non-null  object
 13  Number.of.Engines       82805 non-null  float64
 14  Engine.Type             81793 non-null  object
 15  FAR.Description         32023 non-null  object
 16  Purpose.of.flight       82697 non-null  object
 17  Total.Fatal.Injuries    77488 non-null  float64
 18  Total.Serious.Injuries  76379 non-null  float64
 19  Total.Minor.Injuries    76956 non-null  float64
 20  Total.Uninjured         82977 non-null  float64
 21  Weather.Condition       84397 non-null  object
 22  Broad.phase.of.flight   61724 non-null  object
 23  Report.Status           82505 non-null  object
 24  Publication.Date        73659 non-null  object
dtypes: float64(5), object(20)
memory usage: 17.2+ MB

In [63]:
#Add new column
aviation_data['total_injuries'] = aviation_data['Total.Fatal.Injuries'] + aviation_data['Total.Serious.Injuries'] + aviation_data['Total.Minor.Injuries']

#Create a new column for year to get year trend
aviation_data['Year'] = pd.DatetimeIndex(aviation_data['Event.Date']).year

aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,total_injuries,Year
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,Non-Fatal,Substantial,Airplane,CF-TLU,...,NaN,0.0,0.0,1.0,44.0,VMC,Probable Cause,2017-09-19,1.0,1979
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,Non-Fatal,Substantial,Airplane,N2482N,...,Personal,0.0,0.0,0.0,2.0,VMC,Probable Cause,1982-01-01,0.0,1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,Non-Fatal,Substantial,Airplane,N7967Q,...,Business,0.0,0.0,0.0,2.0,IMC,Probable Cause,1982-01-01,0.0,1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,Non-Fatal,Destroyed,Airplane,N14779,...,Personal,0.0,0.0,1.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,Fatal(1),Destroyed,Airplane,N758SK,...,Personal,1.0,0.0,0.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982

In [65]:
#replace null with 0 total.Fatal.Injuries       Total.Serious.Injuries  Total.Minor.Injuries    Total.Uninjured

aviation_data[['Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries', 'Total.Uninjured', 'Number.of.Engines']] = aviation_data[['Total.Fatal.Injuries','Total.Serious.Injuries','Total.Minor.Injuries', 'Total.Uninjured', 'Number.of.Engines']].fillna(0)

aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,total_injuries,Year
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,Non-Fatal,Substantial,Airplane,CF-TLU,...,NaN,0.0,0.0,1.0,44.0,VMC,Probable Cause,2017-09-19,1.0,1979
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,Non-Fatal,Substantial,Airplane,N2482N,...,Personal,0.0,0.0,0.0,2.0,VMC,Probable Cause,1982-01-01,0.0,1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,Non-Fatal,Substantial,Airplane,N7967Q,...,Business,0.0,0.0,0.0,2.0,IMC,Probable Cause,1982-01-01,0.0,1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,Non-Fatal,Destroyed,Airplane,N14779,...,Personal,0.0,0.0,1.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,Fatal(1),Destroyed,Airplane,N758SK,...,Personal,1.0,0.0,0.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982

In [64]:
#Delete rows where event ID is null
aviation_data = aviation_data.dropna(subset=['Event.Id', 'Model', 'Aircraft.Category'])
aviation_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32254 entries, 5 to 90345
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                32254 non-null  object
 1   Investigation.Type      32254 non-null  object
 2   Accident.Number         32254 non-null  object
 3   Event.Date              32254 non-null  datetime64[ns]
 4   Location                32245 non-null  object
 5   Country                 32242 non-null  object
 6   Injury.Severity         31372 non-null  object
 7   Aircraft.damage         30798 non-null  object
 8   Aircraft.Category       32254 non-null  object
 9   Registration.Number     31970 non-null  object
 10  Make                    32245 non-null  object
 11  Model                   32254 non-null  object
 12  Amateur.Built           32235 non-null  object
 13  Number.of.Engines       28801 non-null  float64
 14  Engine.Type             26708 non-null  object
 15  Purpose.of.flight       27815 non-null  object
 16  Total.Fatal.Injuries    32254 non-null  float64
 17  Total.Serious.Injuries  32254 non-null  float64
 18  Total.Minor.Injuries    32254 non-null  float64
 19  Total.Uninjured         32254 non-null  float64
 20  Weather.Condition       28600 non-null  object
 21  Report.Status           26301 non-null  object
 22  Publication.Date        29606 non-null  datetime64[ns]
 23  total_injuries          32254 non-null  float64
 24  Year                    32254 non-null  int32
dtypes: datetime64[ns](2), float64(6), int32(1), object(16)
memory usage: 6.3+ MB

In [66]:
# Convert date columns
aviation_data['Event.Date'] = pd.to_datetime(aviation_data['Event.Date'], errors='coerce')
aviation_data['Publication.Date'] = pd.to_datetime(aviation_data['Publication.Date'], errors='coerce')
aviation_data.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,total_injuries,Year
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,Non-Fatal,Substantial,Airplane,CF-TLU,...,NaN,0.0,0.0,1.0,44.0,VMC,Probable Cause,2017-09-19,1.0,1979
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,Non-Fatal,Substantial,Airplane,N2482N,...,Personal,0.0,0.0,0.0,2.0,VMC,Probable Cause,1982-01-01,0.0,1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,Non-Fatal,Substantial,Airplane,N7967Q,...,Business,0.0,0.0,0.0,2.0,IMC,Probable Cause,1982-01-01,0.0,1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,Non-Fatal,Destroyed,Airplane,N14779,...,Personal,0.0,0.0,1.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,Fatal(1),Destroyed,Airplane,N758SK,...,Personal,1.0,0.0,0.0,0.0,IMC,Probable Cause,1983-01-02,1.0,1982

In [67]:
risk_summary = aviation_data.groupby('Make').agg({
    'Event.Id': 'count',
    'Total.Fatal.Injuries': 'sum',
    'total_injuries': 'sum'
}).rename(columns={'Event.Id': 'accident_count'}).sort_values(by='accident_count', ascending=False)
risk_summary.head()

        accident_count  Total.Fatal.Injuries  total_injuries
Make
CESSNA            4864                1886.0          3865.0
Cessna            3607                1170.0          2514.0
PIPER             2804                1237.0          2339.0
Piper             1910                 661.0          1346.0
BOEING            1036                2056.0          3529.0

In [68]:
aviation_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32254 entries, 5 to 90345
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                32254 non-null  object
 1   Investigation.Type      32254 non-null  object
 2   Accident.Number         32254 non-null  object
 3   Event.Date              32254 non-null  datetime64[ns]
 4   Location                32245 non-null  object
 5   Country                 32242 non-null  object
 6   Injury.Severity         31372 non-null  object
 7   Aircraft.damage         30798 non-null  object
 8   Aircraft.Category       32254 non-null  object
 9   Registration.Number     31970 non-null  object
 10  Make                    32245 non-null  object
 11  Model                   32254 non-null  object
 12  Amateur.Built           32235 non-null  object
 13  Number.of.Engines       32254 non-null  float64
 14  Engine.Type             26708 non-null  object
 15  Purpose.of.flight       27815 non-null  object
 16  Total.Fatal.Injuries    32254 non-null  float64
 17  Total.Serious.Injuries  32254 non-null  float64
 18  Total.Minor.Injuries    32254 non-null  float64
 19  Total.Uninjured         32254 non-null  float64
 20  Weather.Condition       28600 non-null  object
 21  Report.Status           26301 non-null  object
 22  Publication.Date        29606 non-null  datetime64[ns]
 23  total_injuries          32254 non-null  float64
 24  Year                    32254 non-null  int32
dtypes: datetime64[ns](2), float64(6), int32(1), object(16)
memory usage: 6.3+ MB

In [69]:
#Copy of the csv to export
aviation_data.to_csv('aviation_data_cleaned.csv', index=False)